/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sebas.sistemaexperto;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author hunte
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox7 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        chkFiebre = new javax.swing.JCheckBox();
        chkTos = new javax.swing.JCheckBox();
        chkDolorMuscular = new javax.swing.JCheckBox();
        chkDolorCabeza = new javax.swing.JCheckBox();
        chkEstornudos = new javax.swing.JCheckBox();
        chkSed = new javax.swing.JCheckBox();
        chkCansancio = new javax.swing.JCheckBox();
        chkNausea = new javax.swing.JCheckBox();
        btnDiagnosticar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        jCheckBox7.setText("Sed");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setText("Sistema Experto - Diagnóstico Médico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nombre:");

        txtNombre.setText("Escriba su nombre");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Edad:");

        jLabel4.setText("Sintomas:");

        chkFiebre.setText("Fiebre");
        chkFiebre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFiebreActionPerformed(evt);
            }
        });

        chkTos.setText("Tos");
        chkTos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTosActionPerformed(evt);
            }
        });

        chkDolorMuscular.setText("Dolor_muscular");

        chkDolorCabeza.setText("Dolor_cabeza");
        chkDolorCabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDolorCabezaActionPerformed(evt);
            }
        });

        chkEstornudos.setText("Estornudos");

        chkSed.setText("Sed");

        chkCansancio.setText("Cansancio");
        chkCansancio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCansancioActionPerformed(evt);
            }
        });

        chkNausea.setText("Nausea");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTos)
                            .addComponent(chkFiebre)
                            .addComponent(chkDolorMuscular)
                            .addComponent(chkDolorCabeza)
                            .addComponent(chkEstornudos)
                            .addComponent(chkSed)
                            .addComponent(chkCansancio)
                            .addComponent(chkNausea))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkFiebre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDolorCabeza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDolorMuscular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEstornudos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCansancio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNausea)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane2.setViewportView(txtResultados);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnDiagnosticar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDiagnosticar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkFiebreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFiebreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFiebreActionPerformed

    private void chkTosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTosActionPerformed

    private void chkDolorCabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDolorCabezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDolorCabezaActionPerformed

    private void chkCansancioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCansancioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCansancioActionPerformed

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        // Obtener sintomas seleccionados
    List<String> sintomas = new ArrayList<>();
    
    if (chkFiebre.isSelected()) sintomas.add("fiebre");
    if (chkTos.isSelected()) sintomas.add("tos");
    if (chkDolorCabeza.isSelected()) sintomas.add("dolor_cabeza");
    if (chkDolorMuscular.isSelected()) sintomas.add("dolor_muscular");
    if (chkEstornudos.isSelected()) sintomas.add("estornudos");
    if (chkSed.isSelected()) sintomas.add("sed");
    if (chkCansancio.isSelected()) sintomas.add("cansancio");
    if (chkNausea.isSelected()) sintomas.add("nausea");
    
    if (sintomas.isEmpty()) {
        txtResultados.setText("Seleccione al menos un sintoma");
        return;
    }
    
    // Realizar diagnostico
    List<String> enfermedades = PrologQueryExecutor.diagnosticar(sintomas);
    
    // Mostrar resultados
    StringBuilder resultado = new StringBuilder();
    resultado.append("Paciente: ").append(txtNombre.getText()).append("\n");
    resultado.append("Edad: ").append(spnEdad.getValue()).append("\n");
    resultado.append("Sintomas: ").append(sintomas).append("\n\n");
    
    if (enfermedades.isEmpty()) {
        resultado.append("No se encontraron enfermedades.");
    } else {
        resultado.append("Posibles diagnosticos:\n");
        for (String enf : enfermedades) {
            String rec = PrologQueryExecutor.obtenerRecomendacion(enf);
            resultado.append("- ").append(enf).append("\n");
            resultado.append("  Recomendacion: ").append(rec).append("\n\n");
        }
    }
    
        txtResultados.setText(resultado.toString());
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Cargar Prolog y enfermedades
        PrologQueryExecutor.cargarArchivoProlog("prolog.pl");
        FactsBuilder.cargarEnfermedadesAProlog();
        
        // Abrir ventana
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JCheckBox chkCansancio;
    private javax.swing.JCheckBox chkDolorCabeza;
    private javax.swing.JCheckBox chkDolorMuscular;
    private javax.swing.JCheckBox chkEstornudos;
    private javax.swing.JCheckBox chkFiebre;
    private javax.swing.JCheckBox chkNausea;
    private javax.swing.JCheckBox chkSed;
    private javax.swing.JCheckBox chkTos;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
